# config.yaml

defaults:
    - hydra_basic  # refer to `hydra_basic.yaml`
    - trainer  # refer to `trainer.yaml`
    - module  # refer to `module.yaml`
    - dataset: HCC-WCH  # refer to `dataset/HCC-WCH.yaml`
    - _self_  # 占位符：表示当前文件，在defaults的最后一行声明，可以保证当前文件的配置可覆盖之前的配置

train_loader:
    batch_size: 32
    num_workers: 4
    pin_memory: true
    persistent_workers: true
val_loader:
    batch_size: 8
test_loader:
    batch_size: 8