# trainer.yaml
# This file contains the configuration for the pytorch_lightning.trainer.

callbacks:
    ModelCheckpoint:
        filename: "model_{epoch:02d}_{val_loss:.2f}"
        monitor: "val_loss"
        save_top_k: 3
        mode: "min"
        save_last: True
    EarlyStopping:
        monitor: 'val_loss'
        patience: 5
        mode: 'min'
    TQDMProgressBar:
        refresh_rate: 1
trainer:
    max_epochs: 400
    accelerator: 'gpu'
    devices: 1
    check_val_every_n_epoch: 200
    log_every_n_steps: 1000