# HCC-WCH dataset

data_root : '${oc.env:DATASET_LOCATION, ./data}'
path: '${data_root}/HCC-WCH'

# do resampling to 1x1x1
#transform:
#  ResampleNifti:
#  PermuteDimensions: (2, 0, 1)
#  PadChannels: 220
#  Resize:
#    size: 256
#  CenterCrop:
#    size: 224

# no resampling
transform:
  NiftiToTensor:
  PermuteDimensions: (2, 0, 1)
  PadChannels: 88
  Resize: 256
  CenterCrop: 224


#  Normalize:
#    mean: [0.485, 0.456, 0.406]
#    std: [0.229, 0.224, 0.225]