# HCC-WCH dataset

preprocess_save_path: '${oc.env:DATASET_LOCATION, ./data}/HCC-WCH/preprocessed'

metadata:
  path: '${oc.env:DATASET_LOCATION, ./data}/HCC-WCH/old'
  ext: '.nii.gz'
  name_template: '{patient_number}-{label}'
preprocess:
  test_split: 0.2
  val_split: 0.1
  seed: 42
  # no resampling
  transform:
    NiftiToTensor:
    PermuteDimensions: [2, 0, 1]
    PadChannels: 88
    Resize: 256
    CenterCrop: 224

  # do resampling to 1x1x1
  #transform:
  #  ResampleNifti:
  #  PermuteDimensions: (2, 0, 1)
  #  PadChannels: 220
  #  Resize:
  #    size: 256
  #  CenterCrop:
  #    size: 224


#  Normalize:
#    mean: [0.485, 0.456, 0.406]
#    std: [0.229, 0.224, 0.225]